# Generated by Django 3.0.4 on 2020-03-30 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.IntegerField(default=0)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gu.Participante')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=100)),
                ('grup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gu.Grupo')),
                ('mediador1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gu.Expediente')),
                ('grup', models.ForeignKey(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gu.Expediente'), on_delete=django.db.models.deletion.CASCADE, to='gu.Grupo')),
            ],
        ),
    ]
